DM-14821: mechanisms for packing (some) data IDs into integers
lsst/daf_butler pull request #116
Opened 2019-01-04 19:20 UTC by TallJimbo

2019-01-09 18:46 UTC, natelust requested changes
We talked about moving the packer object lookups onto the registry, and have two different calls to either pick if the given dataId is already equal to the required, and one to just get the packer.

I would like to see that work before this merges.

2019-01-09 18:46 UTC, natelust commented on config/schema.yaml
> +        type: int
How are you sure there is a max like this (and above)? Is it based on the fact that some instruments use 16,32,64,etc bit numbers for identifiers? If so what if an instrument uses say 128, and python int is 64? Or is this int actually a hint to sql and nothing more, and they just have a "number" field. What if a telescope does not use numbers to increment, like some sort of lexographic numbering based on some datestring?

2019-01-09 18:46 UTC, natelust commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +            where = lambda x: True  # noqa
Maybe use _ in the lambda to emphasize that this is never going to be used

2019-01-09 18:46 UTC, natelust commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +    def updateValues(self, other):
So I think it would be good to talk about interior v exterior mutability at some point. If someone reads the documentation for the class, they may take this class as "immutable" but this method implies that it is mutable (though I know it is just interior mutability) however these are not normally python concepts, and someone might be surprised by calling items, getting a list of the items, and then later find that that list does not match what is in the DimensionsKeyDict. I dont' know that we want to disallow this behavior, but it can be surprising, so we should think if this is the ideal structure, or what kind of documentation on the promises this class makes needs to be written.

2019-01-09 18:46 UTC, natelust commented on python/lsst/daf/butler/core/registry.py
>                  # dimension (by normalizing it into a dict-of-sets now).
I think this comment needs updated

2019-01-09 18:46 UTC, natelust commented on python/lsst/daf/butler/core/dataIdPacker.py
> +    # and have to support at least the standard signature.
This message could be clearer

2019-01-09 18:46 UTC, natelust commented on python/lsst/daf/butler/core/dataIdPacker.py
> +                for name, loader in loaders.items():
it is confusing to have loaders be part of a tuple on items in the dictionary named _loaders

2019-01-09 19:44 UTC, timj commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +            where = lambda x: True  # noqa
I thought we frowned upon lambda in this context and preferred:
```python
def where():
    return True
```
?

2019-01-09 19:45 UTC, timj commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +            where = lambda x: True  # noqa
PS `noqa` is meant to include the code that you are ignoring.

2019-01-09 19:47 UTC, timj commented on config/schema.yaml
> +        type: int
The metadata translator constructs the exposure_id as an integer regardless of how the instrument is defining it in the headers. Python integers can be any size.

2019-01-10 01:52 UTC, TallJimbo commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +            where = lambda x: True  # noqa
Agree with `_`.

I generally disagree with PEP8 on local `def` being better than assigning a lambda to a variable (I don't know of any other language with that preference).  Obviously it's a bad idea to pick a fight with PEP8 in general, but relying on a local `def` to shadow a kwarg seemed like a particularly bad idea.  I'll certainly look up the code for `noqa`, though.

2019-01-10 02:01 UTC, TallJimbo commented on config/schema.yaml
> +        type: int
I'm basically reasoning from the other direction: I need an `exposure_max` or something equivalent to implement the ID packers we need to support (Gen2 uses a number of bits, which I think just obfuscates the fact that it defines a maximum exposure number).  So I'm essentially putting it on the `Instrument` subclass (and hence the obs package) to define something and stick to it.  Given the size of even just an int32 and the number of exposures that can practically taken with real instruments of the sort we're trying to support, I don't think that should be a problem.

2019-01-10 02:11 UTC, TallJimbo commented on python/lsst/daf/butler/core/dimensions/dataId.py
> +    def updateValues(self, other):
I had written a brief blurb on this in the `Notes` section of the class doc; I'll expand that.  It does turn out to be a very convenient pattern for the dimension system, in which there are frequently contexts in which the set of dimensions is fixed, and we already have an immutable `Set` class to use as the return value for `keys()`.

2019-01-10 22:20 UTC, TallJimbo commented
@natelust, I've made the changes we discussed, and all of the line comments I didn't respond to have become obsolete as a result.  Please take another look when you get a chance.

2019-01-11 19:30 UTC, natelust approved these changes

2019-01-12 00:07 UTC, merged