Tentative implementation for S3 backed Datastore and RDS backed Registry
lsst/daf_butler pull request #147
Opened 2019-04-23 18:21 UTC by DinoBektesevic

Supports a local Registry and an S3 backed DataStore or a RDS database service
Registry and S3 backed datastore. 

Tests are not yet mocked! The tests for the S3 object storage are likely going to appear end of this week or early next week. Testing RDS seems mission-impossible. 

Currently tests run against an pre-existing bucket and an RDS service. If people are interested, I made the bucket public and I can grant individual IAMs account-based access to the bucket. I can also share the password, username and white-list an IP address of people interested at looking at the RDS PostgreSQL Registry. As long as its only for running the tests of course, downloads and uploads are being charged for. 
The credentials for the bucket are expected to exist in `~/.aws/credentials` and `~/.rds/credentials` files. Both pass `test_butler` and both should pass `test_butlerFits` (S3Datastore+SQLite Registry tested, RDS should follow suite but no test implemented). 

The code is a bit messy - my apologies; but it is meant to start a discussion on the topic of what should the final implementation look like. Comments welcomed. Answers to many questions left as code comments especially welcomed.

2019-04-29 18:37 UTC, timj requested changes
@DinoBektesevic thanks for the pull request.  I have many comments I'm afraid.  Some of these are general problems that I probably need to fix later (such as the code duplication between S3Datastore and PosixDatastore) but most are issues that do need to be fixed before we can merge.

2019-04-29 18:37 UTC, timj commented on config/datastores/s3Datastore.yaml
> +  formatters:
Duplicating all the formatters is clearly not sustainable. I think we probably need to change the `ConfigSubset.defaultConfigFile` to return multiple names so that we can merge your s3Datastore configuration with a posixDatastore one (or maybe pull the formatters out into a separate file in the root config and use `!include formatters.yaml`).

2019-04-29 18:37 UTC, timj commented on config/schema.yaml
> +        length: 16
These changes are on master so a rebase will remove them.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +    def __del__(self):
This and `close()` are no longer required. Please remove (not entirely sure why they are here if you've rebased).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +
Remove this extra line

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/datasets.py
> -
why was this line removed?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> -
put this line back and all the others that were removed.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +
Two lines not three (does flake8 pass?)

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/butlerConfig.py
> +                # I wonder if it would be a good idea to add a 'load' and 'loadFromfile' to
I was expecting this logic to be in `Config` where it sees if it has been given a file.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/butlerConfig.py
> +                    raise ModuleNotFoundError(('boto3 not found.'
I think this should be `raise RuntimeError("Configuration file from S3 not supported")`

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/fileFormatter.py
> +        pickledDataset : `str`
If this is bytes shouldn't it be `bytes` and not `str`?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/fileFormatter.py
> +    def fromBytes(self, pickledDataset, fileDescriptor, component=None):
fileDescriptor is mentioned here but is not documented in parameters.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/fileFormatter.py
> +        pytype : 'class'
This is not an argument to this method.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/fileFormatter.py
> +        pickedDataset : `str`
It should be returning bytes. `pickledDataset` is not the right name. There is no requirement that pickling be involved.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/fileFormatter.py
> +            The bytestring representing the pickled dataset.
It's not a bytestring it's some bytes, and they aren't pickled.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/pickleFormatter.py
> +        pickledDataset : `str`
`bytes` not `str`

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/yamlFormatter.py
> +        pickledDataset : `str`
not pickled. Should be `bytes`.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/yamlFormatter.py
> +            data = pickle.loads(pickledDataset)
This is the yamlFormatter so why is it using pickle?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/yamlFormatter.py
> +        return pickle.dumps(inMemoryDataset, protocol=-1)
YAML formatter should be returning a yaml string encoded to bytes.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/oracleRegistry.py
> -
This line has to be there so put it back.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/postgresqlRegistry.py
> +        super().setConfigRoot(root, config, full)
You don't need to override if all you are doing is calling super().

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/postgresqlRegistry.py
> +    def _createEngine(self):
These hacks with the quoting will hopefully go away very soon with #150

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/postgresqlRegistry.py
> +            localconf.read(os.path.expanduser('~/.rds/credentials'))
there is nothing special about rds here so I don't think we should be using rds in the directory path. @MichelleGower how are you handling passwords for DB access?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/sqlRegistry.py
> +#       [TMPFIX?] I think because I have dimensionless datasettype this instantiation
Remove this and fix up the lines above so that they don't change in this diff.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/sqlRegistry.py
> -
Put this line back.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/registries/sqlRegistry.py
> -
Probably better to put this line back so that it's clear that nothing is changing in this file.

2019-04-29 18:37 UTC, timj commented on tests/config/basic/butler-s3rds.yaml
> +registry: !include rdsRegistry.yaml
For testing we should use sqlite and not even consider rds/postgres.

2019-04-29 18:37 UTC, timj commented on tests/config/basic/rdsRegistry.yaml
> +# Default with a postgreSQL registry
Do not include this file.

2019-04-29 18:37 UTC, timj commented on tests/config/basic/s3Datastore.yaml
> +  templates:
Removing all this duplication is something I need to worry about.

2019-04-29 18:37 UTC, timj commented on tests/config/basic/butler-s3store.yaml
> +registry: !include sqlRegistry.yaml
If this is so you can run in memory with sqlite can you rename it to something like sqliteMemoryRegistry.yaml?

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +import boto3
These three imports have to be protected so that tests can be skipped if they are missing.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        butlerStr = str(butler)
Revert this so that there is no change.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        # is root declared in the self.configFile, which one exactly is this?
Remove this line. You have to declare what the string form of your datastore looks like so you can check to see that S3 (or whatever) turns up when the butler object is stringified.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +@mock_s3
You will probably have to define a no-op `mock_s3` if moto can't be loaded.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +    def setUp(self):
Add a decorator along the line of
```
@unittest.skipIf(not boto3, "Warning: S3 boto is not installed")
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/pickleFormatter.py
> +    def _fromBytes(self, pickledDataset, pytype=None):
My intent was for _fromBytes to be called from _readFile and for _writeFile to call _toBytes, so that we did not get duplication of calls to the serialization code.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        # so there is no recursive Key deleteion functionality either.
deleteion -> deletion

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +    permRoot = 'root/'
Please document these attributes.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +    Very practical for testing the S3Datastore quickly (~6x as fast as RDS setup/teardown).
Remove this comment since it's not describing this test, but describing a separate investigation.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        name for the temporary bucket repo.
Might be worth noting that this is the S3 equivalent of the `tempfile.mkdtemp` calls for the posix datastore.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        # I finally understand, inside MOTO's virtual AWS acc nothing yet exists
This comment needs to be updated.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        if self.useTempRoot:
I don't think you need to check for the case of `useTempRoot == False`.

2019-04-29 18:37 UTC, timj commented on tests/config/basic/s3Datastore.yaml
> +  root: ./butler_test_repository
You need to consider what this should really say.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +        rooturi = f's3://{self.bucketName}/{self.root}'
`BUTLER_ROOT_TAG` would be used if you wanted a scheme whereby you wanted to define the location of your datastore within S3 relative to the location of the butler.yaml file stored in S3. I think you need to consider a scheme where you do support `<butlerRoot>` in S3Datastore so that your default root in config files looks like:
```
root: s3://<butlerRoot>/
```
(whether the `s3://` prefix should be mandatory is something I haven't thought much about).

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +class S3RdsButlerTestCase(S3DatastoreButlerTestCase):
I suggest we drop this from the pull request as it's not part of the S3 functionality.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +        scheme, rootpath, relpath = parsePath2Uri(root)
since rootpath and relpath are not being used it would be simpler to say:
```python
if scheme.startswith("root://"):
    # S3 version
else:
    # File version
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +    if isinstance(config, (ButlerConfig, ConfigSubset)):
This test has already been applied so no need to duplicate it here.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +    # I don't really understand the BUTLER_ROOT_TAG thing
It forces the newly created configuration file to be relative to the butler.yaml file that is being created. This is a reasonable default.  Later on repoRelocation runs to replace `<butlerRoot>` with the actual root calculated from the location of the butler.yaml.  This requires that you have recorded the location of the config file in the `ButlerConfig`.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/butler.py
> +# I didn't want to clog up the butler with more classmethods or a long makeRepo with ifs
There is too much code duplication here.  The S3 stuff involves the serialization of the config and the pushing it to the relevant S3 location. I think that should be moved to `Config` so that you can switch on S3 when deciding whether to write the config file in the file system and calling `config.dumpToFile(os.path.join(root, "butler.yaml"))` or instead calling `config.storeInS3()`.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        self._scheme = scheme+'://' if scheme[-3:]!='://' else scheme
This is not flake8 compliant. Needs some spacing.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        return self.scheme + os.path.join(self._bucket, self._datastoreRoot, self._relpath)
This could forward to `uri` property as is done in `Location`.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +    TODO: This will have broken functionality for extensions etc.
Please explain what you mean by broken for extensions.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        """Update the file extension associated with this `Location`.
`S3Location` not `Location` (this is not a subclass).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +
Too many blank lines (should be 2)

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +    """Factory for `Location` instances.
Factor for S3Location.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        """Factory function to create a `Location` from a URI.
S3Location

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        # uri should alwazs contain scheme, bucket, root, and relpath
"alwazs"

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        # sometimes people give relative path with the datastoreRoot
Who is "people" here?  This comment concerns me since it implies that something is going wrong with S3Datastore or that something is going wrong with PosixDatastore `LocationFactory.fromPath` and I haven't realized yet.  Why are you getting calls to `fromPath` with paths that include the bucket name?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        dirs = path.lstrip('/').split('/')
Why does `os.path.split` not work?  Are you worried that these are URL paths and not posix paths as such and therefore it is possible that `/` is not the separator?  Also, this variable will contain filename as well as directories.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        Returns
Blank line before Returns and `------` after. (I think the original version has the same problem).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +            raise OSError("Don't understand path at all: {}".format(path))
I think it's impossible to get to this else unless nEqual is not >= 0.  Since it starts at 0 and is only ever added to, I don't think this error message can ever be hit.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +            if (d==self._bucket):
If bucket can only ever be first in the list how about:
```python
if dirs[0] == self._bucket:
    dirs.pop(0)
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/location.py
> +        for d in dirs[nEqual:]:
```python
while dirs[0] == self._datastoreRoot:
    dirs.pop()
```
?
then you only need first fromUri call below don't you?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +import boto3
This import needs protecting since boto3 may not be available.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
>             "getObjectSize", "stripIfNotNone", "PrivateConstructorMeta")
Add new functions to `__all__`.

2019-04-29 18:37 UTC, timj commented on tests/test_butler.py
> +    def testPutTemplates(self):
This test is testing template expansion so it's probably okay to remove it here since the template infrastructure is being tested in PosixDatastore.  There's too much code duplication for my liking and I think that we would be unlucky if this test failed and PosixDatastore version passed (assuming the other put tests were working).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +    client : 'boto3.client'
I think these are the wrong quotes. Should be backticks.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +    """
Please document the Returns.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +    # Hopefully multiple identical files will never exist?
datastore.put is meant to check that something isn't already in the datastore using that name. (the template system is meant to be generating unique names).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +# it would be great if this can be better
Maybe remove this comment and add a section in `Notes` in docstring to explain the limitations?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +def parsePath2Uri(path):
The docstring is confusing given the name of the function.   It is documented to take a URI to parse but the argument is called a path. It's not returning a URI at all.  It's parsing the supplied string, that can be a URI or a path to a file.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +    """If the path is a local filesystem path constructs elements of a URI.
One sentence for function overview, then a blank line.

Something like:

"Parse a path or URI into component parts."

and then explain in a notes section or the URI parameter definition what the details are.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +        Posix-like path relative to roothpath.
Posix -> POSIX.
roothpath -> rootpath.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +def s3CheckFileExists(client, bucket, filepath):
If the S3 routines are only used by S3Datastore then they should be moved there. If they are being used elsewhere then I think they should be in their own `s3utils.py` file.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +            root = os.path.abspath(path).split(path)[0]
This doesn't work in the general case (e.g., if path starts with `../`). You need something like:
```python
abspath = os.path.abspath(path)
cwd = os.path.abspath(os.path.curdir)
root = os.path.commonprefix([cwd, abspath])
relpath = abspath[len(root):]
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +def parsePath2Uri(path):
This function needs some tests added for it.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +def bucketExists(uri):
The name is fine if it's in `s3utils` and not general utils package.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/core/utils.py
> +#        # creating new buckets, generalizations hard?
Do not include commented out code.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +import boto3
This import is fine since we only import s3Datastore if we are using an s3Datastore (it's the other boto3 imports that are the ones that need protecting).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.root = replaceRoot(self.config["root"], butlerRoot)
This is the magic you need to sort out if you are enabling repo relocation in S3Datastore.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.s3locationFactory = S3LocationFactory(parsed.netloc, parsed.path)
Since you aren't using the other type of location factory, I think this attribute should be called `locationFactory` (although I see later that you are using internal API for this class so maybe that is not a good idea).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            pass
This `pass` can be removed.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            self.client.get_bucket_location(Bucket=self.bucket)
Probably want a comment here to indicate that the even though it's called `get_bucket_location` we are not interested in the location itself.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.formatterFactory.registerFormatters(self.config["formatters"])
The API for this has recently been simplified to:
```python
        self.formatterFactory.registerFormatters(self.config["formatters"],
                                                 universe=self.registry.dimensions)
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.templates.normalizeDimensions(self.registry.dimensions)
Similarly these two lines are now one:
```python
        self.templates = FileTemplates(self.config["templates"],
                                       universe=self.registry.dimensions)
```

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.name = "S3Datastore@{}".format(self.root)
You have already named yourself above.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.bucket = self.s3locationFactory._bucket
Why is that not using `bucket` property?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                datasetName = location.path.split('/')[-1]
Splitting a path manually on `/` seems risky to me. `os.path.basename(location.path)` seems safer.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                raise ValueError("Failure from formatter for Dataset {}: {}".format(ref.id, e))
I think f-strings would be clearer, and consider saying `from e` at the end here so that it is clear you are augmenting the error message and not raising an entirely new exception.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            pickledDataset = response['Body'].read()
Not necessarily pickled. I think `serializedDataset` might be clearer name.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/formatters/yamlFormatter.py
>      def _writeFile(self, inMemoryDataset, fileDescriptor):
`_writeFile` should probably be reimplemented in terms of `_toBytes` so that things are internally consistent. Possibly `_readFile`/`_fromBytes` as well.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                    raise FileNotFoundError('Could not find dataset {}'.format(location.uri)) from err
I think you need to reraise `err` if it's not a 404 don't you? Otherwise a failure will occur in the next line.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        if hasattr(formatter, '_fromBytes'):
`_fromBytes` is an implementation detail of the file formatter implementation so checking this internal attribute limits the applicability of the bytes code path. 

I was envisaging that unimplemented bytes formatters would raise `NotImplementedError` but clearly that's too late in the game since you need to know whether you are calling an API to pull bytes directly into memory or calling an API to write the bytes first to a file (which presumably is done in a memory efficient manner).  I think this means that we may well have to stop trying to be clever and instead use a class property along the lines of `Formatter.canUseBytes` that is checked here instead.  That's probably preferable to making `_fromBytes` and `_toBytes` part of the public API and insisting they are set to `None` when not implemented.  For the proof of concept the current approach will work.

Regardless, the `Formatter` abstract base class needs to have `fromBytes` and `toBytes` added to it so that formatters that are not inheriting from FileFormatter can still work with S3 and be optimized for it. They should not be abstract but should throw `NotImplementedError` in the base class.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                        raise ValueError("Failure from formatter for Dataset {}: {}".format(ref.id, e))
f-strings preferred I think (which I know is not in the original posixDatastore) and `from e` at the end.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                    raise FileExistsError(f"Cannot write file for ref {ref} as "
This test is presumably unnecessary since you have asked for a temporary directory to be created. `predictedFullPath` is not relevant here.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            with tempfile.TemporaryDirectory() as tmpRootDir:
Are you using a temporary directory rather than temporary file name in order to make it easier to debug (since the file name will be recognizable still).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                with self.transaction() as transaction:
why a transaction here?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +
The new constraints checking code has to be added here to support per-datastore control of whether to accept specific datasets.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        if hasattr(formatter, '_toBytes'):
In this particular case, since we are doing the `toBytes` call early, it's entirely reasonable to put it in a `try` block and call `toBytes` and catch `NotImplementedError` before reverting to file formatter (the transaction would be above them both).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            log.debug("Wrote file to %s", location.uri)
Maybe say "wrote dataset directly to %s" to indicate that you didn't go through a temporary file.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                pickledDataset = formatter.toBytes(inMemoryDataset,  fileDescriptor)
Not pickled.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                datasetName = location.path.split('/')[-1]
Why not `os.path.basename`?  I do agree that in general URIs are not paths but in this case we are retrieving the path component of the URI so it doesn't seem unreasonable to use basename.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                    assert tmpLoc.path == os.path.join(tmpRootDir, tmpPath)
Is this a debug check?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        # ingest is for putting file-like stuff in store. That makes an undefined and 4 defined cases:
Yes. We do need to ingest raw data (which may not have a fully compatible python in-memory equivalent) and some calibration files directly into a datastore without having to go through a Python object.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                #I hope I just don't know how to use urllib or something because this is crap.
The problem seems to be that firstly, there is no standard python class for manipulating the path component of a URI (`furl.Path` seems to try).  In this case URI parsers really do want to treat `root` as a file and `root/` as a directory so they insist that they are different.  I think you have to understand why you are getting the inconsistency that requires these manipulations.  Why can't you normalize `self.root` in the constructor so that it always has the trailing slash to indicate that it's a directory?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            'symlink' indicating how to transfer the file.  The new
This needs fixing to remove hardlink and symlink. I'm not sure that `upload` is needed as such since that is implied by `move` or `copy`.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        elif transfer == 'upload' or transfer == 'copy':
`move` should be allowed. It requires the file to be deleted after upload.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                with self.transaction() as transaction:
`transaction` is not used.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +                self.client.copy(copySrc, self.bucket, relpath)
Should this be a transaction (I admit I don't know what happens to the S3 state if the copy fails).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        #checksum = self.computeChecksum(fullPath)
Checksum can work for the file you have lying around but it's too late to work out it out for the bytes that you uploaded in `put`.  Presumably we could calculate the checksum of the bytes and pass it in as an optional argument to `ingest`, only dealing with files here.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        exists, size = s3CheckFileExists(self.client, location.bucket, relpath)
Is the size of the S3 object different to the size of the file that was uploaded? Or since we are asking for the size from S3 can we check that it's the same as the size of the thing we ingested? Does that matter?

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        self.client.delete_object(Bucket=location.bucket, Key=location.path)
Is it more efficient to call the delete_object directly and catch the exception rather than check and then delete?  Attempting something and catching is usually thought of as being the safe approach if race conditions are possible (something else trying to delete it just after you've deleted it).

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        tmpdir = "/home/dinob/uni/lsstspark/simple_repo/s3_repo"
This doesn't seem to be something we should be committing.

2019-04-29 18:37 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            client.download_file(root, relpath, potentialloc)
Does S3 have an API for you to grab bytes as they come from the server without having to store bytes all in memory? ie can you do "give me N bytes at a time" so that you don't need to download to a temp file. Where is this writing the file?

2019-04-30 00:44 UTC, DinoBektesevic commented on python/lsst/daf/butler/registries/postgresqlRegistry.py
> +            localconf.read(os.path.expanduser('~/.rds/credentials'))
I believe this question was raised in Slack where the response was something down the lines of "Oracle id tokens" but now I can't find it. Ergo the configparse work-around until someone tells me how to do it correctly.

2019-04-30 00:45 UTC, DinoBektesevic commented on tests/test_butler.py
> +import boto3
String and random are builtins I believe, do I have to skip them too?

2019-04-30 01:08 UTC, DinoBektesevic commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        exists, size = s3CheckFileExists(self.client, location.bucket, relpath)
The sizes should be the same. I need the size to create the `StoredFileInfo` two lines down I believe. This is where checksum creation is missing. The file-info is then added to the registry couple of lines down in `self.addStoredFileInfo(ref, fileInfo)`. File-size is later compared to stored file size on retrieval.  So I'm not quite sure what I'm being asked here. We do want at least minimal consistency checks, correct?

2019-04-30 01:14 UTC, DinoBektesevic commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +            client.download_file(root, relpath, potentialloc)
This is all kinds of my-mistakes here. I thought I removed everything from the checksum experimentations here we are. There is a `StreamingBody` object in boto3 I can try and utilize for this purpose.

2019-04-30 01:40 UTC, timj commented on tests/test_butler.py
> +import boto3
No. Sorry for the confusion. It's boto3 that needs to be protected.

2019-04-30 16:40 UTC, timj commented on python/lsst/daf/butler/datastores/s3Datastore.py
> +        exists, size = s3CheckFileExists(self.client, location.bucket, relpath)
Consistency checks are good. It's probably a good idea to compare the size from S3 with the size of the thing you uploaded.

2019-05-17 02:59 UTC, closed without merging